{% set name = "sygnet" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sygnet-{{ version }}.tar.gz
  sha256: 05522d38014914a4c24a153de3a373f7dc1ff2bd13207537852d3df6c2faa368

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - numpy >=1.21
    - pandas >=1.4
    - python >=3.9
    - scikit-learn >=1.0
    - cpuonly
    - pytorch >=1.9.0
    - tqdm
    - flit

test:
  imports:
    - sygnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sygnet/
  summary: Synthetic data using Generative Adversarial Networks
  dev_url: https://github.com/tsrobinson/SyGNet
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tsrobinson
